language: node_js
node_js:
  - '10'

branches:
  only:
    - master

before_install:
  - npm install hexo-cli -g

install:
  - npm install

script:
  # - hexo clean && hexo g && gulp && hexo deploy
  - hexo clean && hexo g && gulp
  - cd public

  # 添加自定义域名
  # - echo 'yechuanjie.com' > CNAME

  - git init
  - git config user.name "yechuanjie"
  - git config user.email "1102684711@qq.com"
  - git add .
  - git commit -m "Update"
  - git push -f "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

notifications:
  email:
    - 1102684711@qq.com
  on_success: change
  on_failure: always